import type { NextPage } from 'next';
import Head from 'next/head';
import { Image, Spin } from 'antd';
import { Carousel } from 'antd';
import React from 'react';

const Portfolio: NextPage = () => {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Carousel autoplay>
            <div>
                <Image preview={false} style={{ display: 'flex', justifyContent: "center", overflowY: "hidden" }} src="/assets/portfolio/portfolio-carousel-pic-1.jpg" placeholder={<Spin tip="Loading"/>} />
            </div>
            <div>
                <Image preview={false} style={{ display: 'flex', justifyContent: "center", overflowY: "hidden" }} src="/assets/portfolio/portfolio-carousel-pic-3.jpg" placeholder={<Spin tip="Loading"/>}/>
            </div>
        </Carousel>
    </>
}

export default Portfolio
